[colors.bright]
black = "#585858"
blue = "#FFAF00"
cyan = "#00AFAF"
green = "#AFD700"
magenta = "#FF5FAF"
red = "#5FAF5F"
white = "#5F8787"
yellow = "#AF87D7"

[colors.normal]
black = "#1C1C1C"
blue = "#5FAFD7"
cyan = "#D7875F"
green = "#5FAF00"
magenta = "#808080"
red = "#AF005F"
white = "#D0D0D0"
yellow = "#D7AF5F"

[colors.primary]
background = "#1C1C1C"
bright_foreground = "#eaeaea"
foreground = "#D0D0D0"

[font]
size = 10

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"
